target_velocity: 1.0
predict_time: 3.0
dt: 0.1
angle_resolution: 0.0087
dist_to_goal_th: 0.3
turn_direction_th: 0.1
angle_to_goal_th: 0.26
max_yawrate_in_situ_turns: 0.4
obs_dist_th: 1.16
velocity_samples: 3
yawrate_samples: 20
